# Generated by Django 4.0.3 on 2022-04-10 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 10, 30, 7, 737318), verbose_name='Token过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 10, 10, 30, 7, 737318), verbose_name='上次登录时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
    ]
