# Generated by Django 4.0.4 on 2022-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='scoreCourseID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
