# Generated by Django 4.0.3 on 2022-04-10 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 11, 49, 2, 173895, tzinfo=utc), verbose_name='Token过期时间'),
        ),
    ]
