# Generated by Django 4.0.3 on 2022-04-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_exp_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exp_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_time',
        ),
    ]
