# Generated by Django 4.0.4 on 2022-05-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_exp_time_remove_user_last_login_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentID', models.CharField(max_length=20)),
                ('departmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='score',
            name='teacherScore',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
    ]
